version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $container_id
# docker-compose logs --tail 20 tf_counts

services:

    udacity-boston-housing-server:
      hostname: jerowe-boston-housing-server
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        HOUSING_DATA: /home/flask/data/housing.csv
      ports:
        - "5000:5000"

    udacity-boston-housing-client:
      build:
        context: .
        dockerfile: Dockerfile-nginx
      volumes:
        - ./html:/usr/share/nginx/html:rw
      links:
        - boston_housing_server
      depends_on:
        - boston_housing_server
      ports:
        - "8081:80"
      networks:
        - app-tier


networks:
  app-tier:
    driver: bridge
