name: boston-housing-prices
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - flask-cors
  - scipy
  - matplotlib
  - jupyterhub
  - scikit-learn
  - numpy
  - pandas
  - ipython
  - gunicorn
